### ISSUE TITLE
obsidian-week-planner

### ISSUE THREAD

**Issue by Steven-AA** [lynchjames/obsidian-day-planner#10]
It would be wonderful to have a week-planner plugin like this.

**Comment by lynchjames** [comment]
Could you provide some more details on how you would see this working for you?

**Comment by Steven-AA** [comment]
Scheduling one day is time consuming and inefficient. As this issue [#2](https://github.com/lynchjames/obsidian-day-planner/issues/2) says "I think that there is no a single person who can finish all task how he planed it".

So I'm used to scheduling important things for each week. As a student, my week's classes, meetings, labs, etc. can be scheduled in advance, and it's a weekly cycle. I can even make a template and do a small amount of adjustments each week. 

Thus I can be clear about my free time to schedule other tasks (done by other task management tools, which I don't necessarily need to write down in this note).

**Comment by wenlzhang** [comment]
As @Steven-AA mentioned, being able to schedule weekly can be very practical. According to the Getting Things Done (GTD) method, it can be very difficult to finish all tasks scheduled for each day, at least very difficult to finish them at the exactly scheduled time, as they can be always more urgent or unanticipated tasks. When this is the case, one may have to move tasks from day to day, which can be time-consuming and inefficient. Therefore, being able to schedule tasks weekly can be more practical.

**Comment by rklasen** [comment]
This sounds fantastic. I would love some way to plan a week or even a month roughly.

**Comment by lynchjames** [comment]
I have posted [an update](https://github.com/lynchjames/obsidian-day-planner/issues/25#issuecomment-739521080) on these request in #25. 

> Thanks for your patience on this. I've given these requests and the related proposal in #10 some thought.
> 
> From the start, I had deliberately intended the Day Planner to be restricted to task planning during the current day for that day's tasks with elements of a simple pomodoro timer. This meant I made some fairly fundamental design decisions for the plugin on that basis.
> 
> I think what is being proposed here and under #10 are really for a separate and much more sophisticated plugin. There is some initial scoping by [tgrosinger](https://github.com/tgrosinger), the author of the [Advanced Tables](https://github.com/tgrosinger/advanced-tables-obsidian) Obsidian plugin, on a plugin that is aimed squarely at these kinds of longer term task and agenda planning requirements, currently named [Agenda for Obsidian](https://github.com/tgrosinger/agenda-obsidian).
> 
> I will be discussing with tgrosinger about my potential contribution to that plugin with some rewritten elements from Day Planner (markdown task parsing, timeline view, status bar, notifications).
