### ISSUE TITLE
The progress bar at the bottom seems to mess with the backlinks pane scrolling

### ISSUE THREAD

**Issue by trongnguyen29** [lynchjames/obsidian-day-planner#11]
If I have the Day Planner turned on, the scrolling through the backlinks pane is messed up. It keeps scrolling down to a previous position while I want to scroll up. My guess is it has something to do with the progress bar, but not sure.

**Comment by lynchjames** [comment]
Could you provide an animate gif of the issue? I've tried replicating the issue from your description but want to make sure I have the backlinks pane in the right position.

**Comment by lynchjames** [comment]
The backlinks pane updates every time a file changes, I think to regenerate backlinks and backlink context. Without any plugins or custom css, this may cause your scroll position in the backlinks pane to reset. You should be able to recreate this by saving a file and observing where the scroll position in the backlinks pane. I've been able to replicate it consistently with the scroll bar near the bottom of the pane.

However, the day planner file was being updated very often, even when there were no changes to content. I've added a check to only update the file when the new contents are different from the current contents. This is more of a mitigation than a fix as the underlying issue appears to be in Obsidian core. I will raise this with the Obsidian developers. Update is in 0.2.4.
