### ISSUE TITLE
Customize gantt chart width

### ISSUE THREAD

**Issue by Rhydderch** [lynchjames/obsidian-day-planner#14]
Hi,

Thank you for this amazing plugin.

Would it be possible to adapt the width of the gantt chart so that it doesn't overflow? Or maybe make it vertical?

![image](https://user-images.githubusercontent.com/3197629/98546295-f4a7ab80-2296-11eb-9228-a1deb463b946.png)

**Comment by lynchjames** [comment]
This has come up recently on the [Obsidian Forum](https://forum.obsidian.md/t/gantt-charts-are-way-too-small-to-be-readable/7017) with a change to Obsidian to not limit the size of mermaid diagrams to the width of a pane.

You could add the following line to your custom css to allow for the gantt chart to fit within the page with a horizontal scrollbar to avoid scaling it down in size resulting in unreadably small text:

```css
.markdown-preview-section .mermaid {
    overflow-x: scroll;
}
```

However, this would affect all mermaid diagrams. This is why I have not added this css to the plugin.

Mermaid does not currently support vertical gantt charts. I am considering an enhancement to display the day planner vertically for #3 so worth keeping an eye on and feeding into that issue.

**Comment by lynchjames** [comment]
This display width of gantt charts has now been fixed in Obsidian version [0.9.14](https://forum.obsidian.md/t/obsidian-release-v0-9-14-insider-build/8530) 😄

**Comment by Rhydderch** [comment]
Great, thank you ! 😄

**Comment by Victorfy** [comment]
still have the problem in obsidian v0.14.6
