### ISSUE TITLE
Can't get timeline to render

### ISSUE THREAD

**Issue by derthnada** [lynchjames/obsidian-day-planner#176]
I've looked through the existing issues, but I can't get the Timeline to render at all. I'm on Obsidian 0.15.9 on Mac. 

I've tried:

- file mode, using the autogenerated directory and daily file, with my own and the example md
- file mode, moving the daily file out into the root directory (per another issue)
- command mode, unlinking and linking the planner to the current note, both in the autogenerated files and elsewhere
- disabling any plugins that deal with pane management, lists, time/dates

In all of these situations, when I select "Show the Day Planner Timeline" from the command palette, nothing happens. No new pane is displayed, there's no error message, nothing in the developer's tool console, just...nothing. I wish I had more data to give you, but there isn't any.

**Comment by la-lessia** [comment]
This is happening with me too!

**Comment by lukemt** [comment]
same for me, it does work though if i click this icon afterwords:
<img width="1792" alt="Day Planner Icon" src="https://user-images.githubusercontent.com/3893274/184477106-b72c56bf-0c9c-4cfe-96e5-2fb77ccad81b.png">

Does this work for you too?

**Comment by shmuhammad2004** [comment]
Hi, I spent sometime trying to figure this out. I cannot see the timeLine yes.
