### ISSUE TITLE
Do not remove sub bullets

### ISSUE THREAD

**Issue by nhdhung** [lynchjames/obsidian-day-planner#19]
Thanks for the nice plugin @lynchjames.

Personally I prefer using "Day Planner" with the following setup so that I can re-schedule my tasks easily in case of some unexpected events (by moving lines up and down with some hotkeys)

```md
# Day Planner

**Current Task**
- [ ] 08:00 - Morning tasks
	- [ ] Workout
	- [ ] Daily note
		- Some random note
		- Some random ideas
		- Some random ideas

> ||08:00||->->->->->->->->->->_ _ _ _ _ _ _ _ ||09:00||

- [ ] 09:00 - Work
        - [ ] Standup
	- [ ] Plan the day
- [ ] 10:00 - Task 1
---
```

Thus, is it possible to keep lines with sub bullets in a future release? Thanks.

**Comment by lynchjames** [comment]
These should be supported in [0.3.3](https://github.com/lynchjames/obsidian-day-planner/releases/tag/0.3.3).
