### ISSUE TITLE
Why don't we make a community fork?

### ISSUE THREAD

**Issue by m-antis** [lynchjames/obsidian-day-planner#214]
Is @lynchjames even still alive?

**Comment by jtbg** [comment]
be the maintainer you wish to see in the world :)

**Comment by ivan-lednev** [comment]
Hello, @m-antis,

I've forked the project recently, and I'm planning to add the fork to the community plugins in the nearest weeks. I've rewritten the UI and I'm planning to work through the most obvious issues first, so hang in there tight! 😄 

![image](https://github.com/lynchjames/obsidian-day-planner/assets/41428836/e0f77d72-5e1d-4fa7-9fb1-4f20fd577e30)

**Comment by benjamonnguyen** [comment]
@ivan-lednev let me know if you are open to contribution on your fork, I'd love to implement a configurable time format or other priority task.

**Comment by ivan-lednev** [comment]
Hi, @benjamonnguyen, I'm definitely open to contribution. Feel free to create an issue in the repo, and I'll notify you once the code is in good enough shape for others to contribute to.

**Comment by benjamonnguyen** [comment]
@ivan-lednev gotcha, can you enable issues?

**Comment by ivan-lednev** [comment]
@benjamonnguyen, here you go: https://github.com/ivan-lednev/obsidian-day-planner/issues

**Comment by ivan-lednev** [comment]
To anyone interested, [my fork](https://github.com/ivan-lednev/obsidian-day-planner) can now be installed via BRAT. Issues and pull-requests are welcome.

**Comment by lynchjames** [comment]
I am still alive!! I've reached out to @ivan-lednev to discuss some next steps. We will update here very soon.

**Comment by lynchjames** [comment]
@ivan-lednev and I have discussed the progress he has made with his [long-running fork](github.com/ivan-lednev/obsidian-day-planner) where he has made significant improvements and added new features. 

We have agreed for me to transfer ownership of this repo to him to allow him to carry on and make updates to the plugin in the near future.
