### ISSUE TITLE
How to Not AUTO Complete Past Planner Items

### ISSUE THREAD

**Issue by Raynchowkw** [lynchjames/obsidian-day-planner#216]
as readme says, we can choose to not automatically complete past items.
How to do this?
Where can I find the command? Or what code should I learn?
Thanks.

**Comment by BGvdS** [comment]
If you go to the _Settings_ menu, click on _Day Planner_ in the left column. The second option (and first toggle), _Complete past planner items_ should be off (to the left). This should solve your issue.

**Comment by Raynchowkw** [comment]
Got it.
