### ISSUE TITLE
Some initial feedback after testing it out

### ISSUE THREAD

**Issue by liamcain** [lynchjames/obsidian-day-planner#22]
Hi! Just started trying out the plugin so I hope you don't mind the feedback! (In no particular order)

##  UX
- ❓ Any reason why you're using system notifications instead of Obsidian's `Notice`?
- The README currently has a lot in it that it's a bit overwhelming to get started.
  - Maybe start off with a list of features first (that way I know what I should read more about)
  - While I don't quite understand the nuances between the 2 'modes', it might be simpler to just have a toggle between "use separate notes" vs. "use daily notes" because I was pretty confused by "File Mode" and "Command Mode" when I saw it.
- ❓ Why do you need the `hr` to find the end of the planner? Couldn't you just use the position of the next header (you could use the filemetadata rather than parsing the file yourself here)
- Instead of having a "Track current time checkbox" I think this would make sense to mimic something like Google Maps -- if you scroll, disable the tracking, then make a button appear that says "Track" to re-enable tracking. Currently the behavior when you scroll while tracking is enabled feels broken.

## Dev
- 🎨 Looks like there is a leftover console.log heartbeat polluting the console
- You don't need `normalizePath` anymore, you can now use the exported normalizePath function from obsidian (`import {normalizePath} from 'obsidian';`)

## Bugs maybe?
- It shows a status menu item that says "ALL DONE" and an empty tooltip for my note?
- When I try to complete a task, the file gets rewritten and it is no longer marked as complete? Is there something I'm missing to 'complete' a task (I'm just typing 'x' in the `- [ ]` markdown)

**Comment by lynchjames** [comment]
Thanks very much for this great detailed feedback @liamcain! Along with issues others have been raising, it has helped a lot in (hopefully) improving the plugin. 😄 

Here are some responses with updates from fixes and improvements in [0.5.3](https://github.com/lynchjames/obsidian-day-planner/releases/tag/0.5.3):

## UX

- The Notice from the Obsidian API doesn't appear to support line breaks or the separation of title from body content, as is supported by the system notifications. This is needed for the amount of info being displayed for the current and next task.
- I need to sort out the README as it has become pretty cluttered as I've added to it for new features and configuration settings. I've added a features section at the top for now and will break it down into separate markdown files soon.
- The hr or `---` was being used previously to select the portion of the note to parse and then completely rewrite. This was too intrusive and was causing other issues (#24, #27) so I have changed the approach to be much lighter touch in rewriting only what is needed and now the hr is no longer required.
- The "Track current time" option is now automatically turned off when the user scrolls to give the better sort of behaviour you suggested.

## Dev
- Caught the console.log in an earlier release.
- I noticed this was available from the Obsidian API but hadn't got around to replacing it. Now updated in 0.5.3.

## Bugs
- I know of the bug with empty tooltip in some cases. I will raise a separate issue for that. "ALL DONE" should be shown when the current time is later than the time of the END task. It may be shown in other scenarios which would also be a bug. I will look into it.
- There is a config setting to [complete past planner items](https://github.com/lynchjames/obsidian-day-planner#complete-past-planner-items). If it is enabled, task items that occur in the past will be automatically checked and task items that are in progress or in the future will be automatically unchecked. I should update the README to make it more clear that this will update all tasks in this way.

**Comment by lynchjames** [comment]
And on the File Mode vs Command Mode and making the difference more obvious and user friendly, I will address this when I change to use the daily notes core plugin setting for note location instead of a Day Planner specific one (#20).

**Comment by liamcain** [comment]
Awesome, thanks for the detailed response. I just started playing with the updated version now, will let you know if I have any more feedback!
