### ISSUE TITLE
Progress bar disappeared (after 0.5.2?)

### ISSUE THREAD

**Issue by psyguy** [lynchjames/obsidian-day-planner#27]
Hi,
Thanks for the fascinating plugin!

The plugin used to work for me just fine until two days ago (maybe before updating the plugin to 0.5.2 or Obsidian to 0.9.11?). Now, although it shows progress in the note (in the form of `||12:20||->->->_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ ||14:40||`) it has stopped showing anything in the status bar (the [circular] progress bar, _Now sand Next_).

P.S. I do not use Mermaid charts often, but this is the error in teh preview mode I got when I activated it now:

```
Error parsing Mermaid diagram!

Parse error on line 6:
..., 30mm    call     :11-15, 65mm    bac...
----------------------^
Expecting 'EOF', 'SPACE', 'NL', 'dateFormat', 'inclusiveEndDates', 'axisFormat', 'excludes', 'todayMarker', 'title', 'section', 'taskTxt', 'click', 'open_directive', got 'callbackname'
10:45 first thing
```

To make it reproducible, here is how the planner looks like right now:

```
## Day Planner

- [x] 10:45 first thing
- [x] 11:15 call

**Current Task**

> ||12:20||->->->_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ ||14:40||

- [ ] 12:20 back to work
- [ ] 14:40 moving the laundry
- [ ] 15:00 back to work
- [ ]  
---
```

Is there a fix for these issues? Thanks in advance!

---
**Update:**

I used the [example day planner example on this repo](https://github.com/lynchjames/obsidian-day-planner/edit/main/examples/day-planner-example.md) and the Mermaid diagram renders just fine. However, the issue wuth status bar still remains.

**Comment by lynchjames** [comment]
This is caused by there not being an extra line before the terminating `---`. I'm going to look at changing the format requirements to not depend on these terminating characters but, in the meantime, you can workaround this issue by having this:

```
## Day Planner

- [x] 10:45 first thing
- [x] 11:15 call

**Current Task**

> ||12:20||->->->_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ ||14:40||

- [ ] 12:20 back to work
- [ ] 14:40 moving the laundry
- [ ] 15:00 back to work
- [ ]  

---
```  

instead of this:

```
## Day Planner

- [x] 10:45 first thing
- [x] 11:15 call

**Current Task**

> ||12:20||->->->_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ ||14:40||

- [ ] 12:20 back to work
- [ ] 14:40 moving the laundry
- [ ] 15:00 back to work
- [ ]  
---
```

**Comment by lynchjames** [comment]
The terminating `---` is no longer required as of release [0.5.3](https://github.com/lynchjames/obsidian-day-planner/releases/tag/0.5.3).

**Comment by psyguy** [comment]
Thanks James, it works great now 😌
