### ISSUE TITLE
Day Timeline is huge and mostly empty

### ISSUE THREAD

**Issue by rklasen** [lynchjames/obsidian-day-planner#28]
Hi,

The timeline to the right is very very long and for the most part empty:

![image](https://user-images.githubusercontent.com/13201731/99787151-abb9e780-2b1f-11eb-9244-8a8e353be5c5.png)

For the longest time I didn't even realize that is a timeline view until I scrolled down:

![image](https://user-images.githubusercontent.com/13201731/99786927-60073e00-2b1f-11eb-86f1-9880044407b6.png)

There is also a huge empty gap at the end. It looks like the timeline is just going from 00:00 to 23:59, even if most of it is empty.

Is there a way to remove the empty space and condense the actual tasks a little? Ideally a days plan (say 9:00 to 21:00) would fit into a FHD monitor vertically.

Also please note how I had to turn "Track current time" off, because id that is on, the timeline always scrolls to the empty top, even though the red line for the current time is at the correct position.

Thanks!

**Comment by lynchjames** [comment]
This should be resolved in [0.5.3](https://github.com/lynchjames/obsidian-day-planner/releases/tag/0.5.3).
