### ISSUE TITLE
Feature Request -- persistant task notifications like MacOS reminders?

### ISSUE THREAD

**Issue by tallguyjenks** [lynchjames/obsidian-day-planner#29]
Would it be possible to have the notifications for the start of the next task, have an option to linger until manually dismissed by the user?

**Comment by lynchjames** [comment]
I tried using the `requiresInteraction` option when creating a notification but it was ignored. It looks like this is a [known issue with electron](https://github.com/electron/electron/issues/9283).

**Comment by tallguyjenks** [comment]
lol @lynchjames i hate how often i see the exact words 
> "known issue with electron."

🤣 🤣 🤣

**Comment by fakeharxy** [comment]
just to say - I seem to get the functionality you want by changing the notifications from "Banners" to "Alerts" in notification settings. Don't know if this is helpful/what you are looking for.

**Comment by tallguyjenks** [comment]
@lynchjames it works :)
