### ISSUE TITLE
Side bar view [idea]

### ISSUE THREAD

**Issue by dxcore35** [lynchjames/obsidian-day-planner#3]
Maybe you can utilize code from this project: https://khrykin.github.io/StrategrDesktop
To have it in the Obsidian as side bar will be mind blowing.

<img width="412" alt="68747470733a2f2f6b6872796b696e2e6769746875622e696f2f53747261746567724465736b746f702f6173736574732f7265736f75726365732f6d61635f626c61636b5f6d61696e2e706e67" src="https://user-images.githubusercontent.com/7279156/98311455-d3785e00-1ffd-11eb-98ed-1eb21c5a7c77.png">

**Comment by lynchjames** [comment]
This is now available in [0.5.0](https://github.com/lynchjames/obsidian-day-planner/releases/tag/0.5.0).

**Comment by dxcore35** [comment]
Wau, wau and wau.

**Comment by Rhydderch** [comment]
This is amazing, well done/ thanks a lot!

**Comment by ib0o0** [comment]
> This is now available in [0.5.0](https://github.com/lynchjames/obsidian-day-planner/releases/tag/0.5.0).

This is not showing up in my Obsidian (0.9.19) running on MacOS 10.15.7 
[Calendar icon not showing up here](https://imgur.com/a/XLFYfy5)

- [ ] I tried uninstalling the Calendar plugin
- [ ] I restarted the app

As far as I can tell, there is no option to activate or deactivate your timeline view.

What might I be doing wrong?

**Comment by alexllc** [comment]
> > This is now available in [0.5.0](https://github.com/lynchjames/obsidian-day-planner/releases/tag/0.5.0).
> 
> This is not showing up in my Obsidian (0.9.19) running on MacOS 10.15.7
> [Calendar icon not showing up here](https://imgur.com/a/XLFYfy5)
> 
>     * [ ]  I tried uninstalling the Calendar plugin
> 
>     * [ ]  I restarted the app
> 
> 
> As far as I can tell, there is no option to activate or deactivate your timeline view.
> 
> What might I be doing wrong?

Have you tried setting a custom hot key in "option > Hotkeys > Day Planner: Show the Day Planner Timeline" and toggling it?
