### ISSUE TITLE
Feature Request: Option to hide indicator in status bar

### ISSUE THREAD

**Issue by LucasD3** [lynchjames/obsidian-day-planner#30]
It would be great to be able to hide the "x mins left" indicator in the status bar, for moments when one wants to focus in on writing.

**Comment by lynchjames** [comment]
There is a setting to [show some of the text for the current and next task](https://github.com/lynchjames/obsidian-day-planner#status-bar---now-and-next) instead of "x mins left". Would that work for this or are you looking for a setting to only display the progress bar in the status with no text?

**Comment by LucasD3** [comment]
Sorry I wasn't very clear. The current status bar implementation is great as is. But sometimes, when I want to focus on writing, I would prefer not to have anything displayed in the status bar at all. Since there doesn't seem to be an option in Obsidian (yet) to toggle the status bar on and off, I'm hoping there could be an option to tell Day Planner not to display anything in the task bar.

**Comment by LucasD3** [comment]
Ah, it turns out there is [a plugin already for hiding UI elements](https://github.com/kepano/obsidian-hider), including the status bar! So I think I'm all set for now. (Feel free to close this issue.)

**Comment by lynchjames** [comment]
Ok, sounds like a good option. Will close this issue.
