### ISSUE TITLE
Native Reminders/Calendar Integration

### ISSUE THREAD

**Issue by urishiraval** [lynchjames/obsidian-day-planner#32]
Hey Guys...excellent work with this plugin!

How keen are you to maybe add functionality to sync the planner with a calendar or reminders app (or even better, both)?

I made an [Apple Reminders](https://github.com/urishiraval/obsidian-apple-reminders-plugin) plugin for obsidian a few weeks ago but using that and this plugin is becoming redundant for me. I wouldn't mind depreciating that repo and integrating it that into this plugin. I would also be happy to maintain the functionality in the future if you guys are up to it.

I have a plan of how to port the backend business logic from that repo and essentially it would be a 'plugin' to a 'plugin' that wouldn't effect the UI much (if at all).

Lemme know what you guys think about this

**Comment by tallguyjenks** [comment]
➕💯

**Comment by shiddy** [comment]
Hey @urishiraval not sure if this is something that was closed intentionally, but I would also like to express that if there was a way to get native Apple reminders synced with the day-planner plugin.

**Comment by urishiraval** [comment]
Hey @shiddy, there definitely is....I've just been too busy to complete my packaging of the Reminders plugin to get it to a state where it can be plugged into other plugins

But I am going to start maintaining the repo better from now on so hopefully it won't be long before it's ready to be integrated into these other cool plugins
