### ISSUE TITLE
Hotkey to open day planner note

### ISSUE THREAD

**Issue by Quorafind** [lynchjames/obsidian-day-planner#33]
When I wanted to open my day planner note, I had to search the day planner note and then organize my daily task.
I don't know if it is possible to open day planner note directly.

**Comment by lynchjames** [comment]
You can access the day planner note by clicking on the task info and/or progress bard in the status bar.

I can also add a command to open the note for the day planner.

**Comment by lynchjames** [comment]
A command is available in [0.5.5](https://github.com/lynchjames/obsidian-day-planner/releases/tag/0.5.5) to show the note for the day planner which can be bound to a hotkey.
