### ISSUE TITLE
Red vertical line does not move in gantt chart

### ISSUE THREAD

**Issue by hrpomrx** [lynchjames/obsidian-day-planner#34]
I see the tasks update, get checked when done, and the current task bar moving dynamically, but the red vertical line in the gantt chart just stays put; it would be nice if it would move itself along the gantt chart too as time progresses. I am able to get it to update by closing the preview and reloading it.

**Comment by lynchjames** [comment]
I can include the current time in a comment within the mermaid code which will cause the gantt chart to re-render around every 8 seconds causing the position of the vertical line to update.

**Comment by lynchjames** [comment]
This should now be available in the latest release ([0.5.4](https://github.com/lynchjames/obsidian-day-planner/releases/tag/0.5.4)).
