### ISSUE TITLE
Toggle Markdown Current Task progress bar

### ISSUE THREAD

**Issue by xitizmandal** [lynchjames/obsidian-day-planner#38]
Is there any way to have the markdown progress bar removed? Or atleast have it toggle on and off like the gantt chart? 

```
||15:45||->->->->->->->->_ _ _ _ _ _ _ _ _ _ ||17:45||
```
It triggers the note to sync everytime when the progress is changed. It can be annoying at times to have the histories (esp when syncing in git)

**Comment by lynchjames** [comment]
This has been removed in release [0.5.3](https://github.com/lynchjames/obsidian-day-planner/releases/tag/0.5.3). What version are you using?

If you are using 0.5.3, can you disable and then re-enable the plugin? There may be an issue with it not being fully loaded with the updated version.

**Comment by xitizmandal** [comment]
I was on 0.5.2 . I updated it to release 0.5.3 . And it's working like I wanted to

Thanks a lot.
