### ISSUE TITLE
Prepending checkboxes to lines

### ISSUE THREAD

**Issue by spencercook** [lynchjames/obsidian-day-planner#42]
If I have a line of text that begins with `HH:mm`, the Day Planner prepends `- [ ] ` to that line. I thought I could avoid this by putting the line beyond the extents of the Day Planner area (before `# Day Planner` or after `---`) but it doesn't matter- it prepends it regardless of location within the note.

Is this working as intended? Thanks, really enjoying it besides this minor issue.

**Comment by lynchjames** [comment]
This should be fixed in [0.5.8](https://github.com/lynchjames/obsidian-day-planner/releases/tag/0.5.8).
