### ISSUE TITLE
Unable to add new line to end of note

### ISSUE THREAD

**Issue by Joe1177** [lynchjames/obsidian-day-planner#45]
Since V0.5.7 I am unable to add a new line after the last line of the note. So if the note is:

```
...
- [ ] 17:00 END

## Notes
Hello World
```
With the cursor at the end of the last line (...orld|) if I press return the cursor jumps to a new line but as soon as I start typing the carriage return is removed and it jumps back to the end of (...orld|) with the letter just typed. 

This is when I have linked a note via the command.

**Comment by lynchjames** [comment]
I can't replicate this issue using either file or command mode. Which version of Obsidian are you currently using?

Could you try reinstalling the plugin to see if that resolves the issue?

**Comment by Joe1177** [comment]
On V0.9.22 I've been unable to replicate it since restarting Obsidian, will close the issue for now and see if it crops back up again. Thanks for the plugin!
