### ISSUE TITLE
Break and End keywords not recognized

### ISSUE THREAD

**Issue by masasin** [lynchjames/obsidian-day-planner#48]
Hello! I'm using the plugin on 9.20, and the Break and End keywords aren't recognized anymore. Everything goes in the same section on the Gantt chart, and uses the same template in the status bar.

I'm not sure what information you'd need to investigate/reproduce. Please let me know!

(The plugin works great as is, so long as the Gantt chart is hidden.)

**Comment by timjore** [comment]
I am seeing the same unexpected behavior in Obsidian 0.9.22 and Day Planner 0.5.7. I have tried reinstalling the plugin, but the behavior is the same.

**Comment by lynchjames** [comment]
I have a fix for the Break parsing which cause breaks to not be identified for either the Mermaid Gantt chart of status bar message.

I couldn't replicate the issue with the End keyword though. The End item was always included in the Tasks section of the Mermaid Gantt chart.

**Comment by lynchjames** [comment]
The fix for the Break keyword is in [0.5.8](https://github.com/lynchjames/obsidian-day-planner/releases/tag/0.5.8).
