### ISSUE TITLE
Bug: Day Planner Pane not visible 

### ISSUE THREAD

**Issue by sidgangal** [lynchjames/obsidian-day-planner#51]
Great plugin @lynchjames! Love the thought and it makes obsidian incredily useful for my daily flow.

I'm not able to use the Dayplanner pane feature.

It shows a blank.

I think it might be due to mermaid not working in obsidian.

![image](https://user-images.githubusercontent.com/8455605/103176832-1ab2fa80-489b-11eb-9773-e5057c340043.png)

Thank you.

System:
M1 Chip Macbook Air
ARM 0.10 Beta

**Comment by Daydog** [comment]
Hi, Day Planner Pane not visible as well
System: Win 10
Surface Pro 7

**Comment by sidgangal** [comment]
Closing this issue. It just started working itself. 

Maybe it self-resolved after a restart/
