### ISSUE TITLE
Question: Layout of status bar

### ISSUE THREAD

**Issue by dgonzo** [lynchjames/obsidian-day-planner#59]
The layout of Day Planner status bar is cramped. Is there a plugin setting that I can use to fix this? 
<img width="1282" alt="Screenshot_1_29_21__1_38_PM" src="https://user-images.githubusercontent.com/361559/106325047-6a3c6b80-6237-11eb-8bac-c30566782f19.png">

**Comment by lynchjames** [comment]
There is a plugin setting to [display the Now and Next in the Status Bar](https://github.com/lynchjames/obsidian-day-planner#status-bar---now-and-next) which you can turn off.

![image](https://user-images.githubusercontent.com/113271/122654282-5213ad00-d142-11eb-8ff3-f3ee1b86e9ce.png)
