### ISSUE TITLE
Timeline view does not account for daylight savings time

### ISSUE THREAD

**Issue by awmottaz** [lynchjames/obsidian-day-planner#69]
Here in the Central Time Zone, we just started daylight savings time. It appears that the timeline view for this plugin does not correctly account for this. The current time marker is correct, but it is shown 1 hour in the past on the time blocks.

<img width="297" alt="Screen Shot 2021-03-15 at 09 22 48" src="https://user-images.githubusercontent.com/17735385/111168386-07e1c500-8570-11eb-8429-60a7dc7378ab.png">

**Comment by awmottaz** [comment]
Huh, seems to be fine now. Might have been a glitch.

**Comment by donthorp** [comment]
Central Timezone as well. We switched today Nov 5, 2023 and the problem is still there. I'm betting since it self corrected 2 days later, that it is off by 24 hours or so.

**Comment by kahboom** [comment]
Just wanted to add that it's still happening

**Comment by db30x** [comment]
any fixes?
