### ISSUE TITLE
Status bar enhancement

### ISSUE THREAD

**Issue by Quorafind** [lynchjames/obsidian-day-planner#7]
it only shows how many minutes left but I also want to check what I planned to do for this period on the status bar.
For example:
`Recent task` 40 mins left [|||||||||||&emsp;&emsp;] `Next task`
It is useful for me when I focus on writing.

**Comment by dxcore35** [comment]
Maybe just text will be even better?

```Recent task (95%)``` >>> ```Next task```

**Comment by Quorafind** [comment]
@dxcore35 Or give a option to choose which one ? I think showing the left mins is useful for me to know the time.

**Comment by dxcore35** [comment]
Yes. the time is better.

```Recent task (-5min)``` >>> ```Next task```

Let's not bother the dev for giving so many customisation yet :D Maybe after v1 the functions can be more customised.... otherwise development of core functions will take ages.

**Comment by lynchjames** [comment]
Some great ideas here!

A few separate things that could be done.

Keep the time remaining in the status bar but present a % (e.g. 95% as text over the progress bar itself). This could be done once the percentage reaches a certain minimum to make sure there are not issues with rendering the text over the boundary between the filled and unfilled portion of the progress bar. Here's an example:
![image](https://user-images.githubusercontent.com/113271/98446996-7e316f00-2119-11eb-8aa7-3f27629929e1.png)

I'm conscious of not taking up too much space within the status bar which may include other things such as backlinks, word count, git status (from other 3rd party plugin) etc.

The information on the current task and next task could be presented within a card that would be displayed on hovering over the status item, e.g.:
![image](https://user-images.githubusercontent.com/113271/98447342-129cd100-211c-11eb-86ec-d45684302bf6.png)

**Comment by dxcore35** [comment]
It is very very good idea! @lynchjames 

## But

- can you make the width of the progress bar smaller? 
- or can you make it circular? by this it will take even less space

**Comment by Quorafind** [comment]
Seems like so cool, I think it is enough for me. But if people could change the view mode of this, things can be better?

**Comment by lynchjames** [comment]
> It is very very good idea! @lynchjames
> 
> ## But
> * can you make the width of the progress bar smaller?
> * or can you make it circular? by this it will take even less space

The width could be reduced, I just picked 150px because it seemed about right but no better reason! 

The height is also pretty constrained on the status to > 18px _but_ I think that would be enough for a small circular progress bar.

I'll try something out think of a few display options for the status bar.

**Comment by dxcore35** [comment]
You are amazing!

**Comment by lynchjames** [comment]
A couple of different status bar layout combinations are now available in [0.3.2](https://github.com/lynchjames/obsidian-day-planner/releases/tag/0.3.2).
