### ISSUE TITLE
Track current time not showing properly

### ISSUE THREAD

**Issue by Redencon** [lynchjames/obsidian-day-planner#71]
Right now, if the width of the timeline window is too small, the switch of «Track current time» goes beneath the status bar and is almost impossible to click.

![изображение_2021-03-29_205442](https://user-images.githubusercontent.com/55309680/112878763-fc92ab80-90d0-11eb-8a9b-ff1fbeec0ab4.png)

**Comment by lemonbirdy** [comment]
I am having the same issue. The status bar overlaps with the track current time toggle. Do you know how to solve it?

**Comment by SkyStreet** [comment]
same issue happens, worse still, completely shadowed by status bar.
