### ISSUE TITLE
Current task (progress bar) as mini Mermaid diagram

### ISSUE THREAD

**Issue by dxcore35** [lynchjames/obsidian-day-planner#9]
I was thinking if the current task and next task should be shown in diagram:

```
gantt
    title A Gantt Diagram
title Day Planner for 6 November 2020
    dateFormat  HH-mm
    axisFormat %H:%M
    section NOW
    Setup      :16-08, 52mm
    Writing blog post      :17-00, 60mm
```
And remove the current progress indicator

```
> ||14:00||->->->->->->->->->->_ _ _ _ _ _ _ _ ||15:00||
```

- This will force you to focus more on current task and prepare mentally :D for the next one. And it is more beautiful and obvious then textual progress bar.
- Probably you can add Mermaid CSS class into div class and change width of display....just thinking aloud.
- It also can be option to toogle between two displays (old and mermaid) in settings...but as you are developer maybe it will be prober to not give so much control for user, just chose the one style that is best for clarity.

**Comment by lynchjames** [comment]
The progress bar in the markdown note has been removed in [0.5.3](https://github.com/lynchjames/obsidian-day-planner/releases/tag/0.5.3).

@dxcore35 are you still looking for this change to the Mermaid gantt chart for the current and next task in a separate group with the timeline view now in place?

**Comment by dxcore35** [comment]
Actually no. When seeing the Mermaid chart I can directly see where Im right now. And more details is now in status bar. I'm ok to not have anything inside body text area.

**Comment by lynchjames** [comment]
Ok, thanks for confirming. I will close this issue.
