### ISSUE TITLE
Timeline view wont open

### ISSUE THREAD

**Issue by Deottive** [lynchjames/obsidian-day-planner#90]
I have tried installing the plugin again and again but it does not open and also I dont know where I should put the command

**Comment by FranzSkuffka** [comment]
I have the same problem. I execute it from the command palette but it does not show the timeline. Mermaid gantt works...

**Comment by FranzSkuffka** [comment]
@Deottive I figued it out. it was hidden in the right sidebar behind the little arrow.

**Comment by tyePhDCandy** [comment]
> @Deottive I figued it out. it was hidden in the right sidebar behind the little arrow.

eh, where is this right sidebar behind the little arrow ???? please tell me , i cant figure it out.
![image](https://user-images.githubusercontent.com/22343659/221462912-ea725ebc-546b-4aa8-8236-302c89d864bf.png)

**Comment by tyePhDCandy** [comment]
o, i see. You must follow some format to let timeline feature happen. thanks.
![image](https://user-images.githubusercontent.com/22343659/221464321-e6d44e1e-56da-482f-a0b5-d45e5068ae00.png)
